allowBuilds:
  sharp: false
  unrs-resolver: false

blockExoticSubdeps: false

minimumReleaseAgeExclude:
  - '@better-auth/core@1.7.6'
  - '@better-auth/drizzle-adapter@1.7.6'
  - '@better-auth/kysely-adapter@1.7.6'
  - '@better-auth/memory-adapter@1.7.6'
  - '@better-auth/mongo-adapter@1.7.6'
  - '@better-auth/prisma-adapter@1.7.6'
  - '@better-auth/telemetry@1.7.6'
  - auth@1.7.6
  - better-auth@1.7.6
